### ISSUE TITLE
Colocar campo código de cliente en el formulario de crear cliente

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#250]
En el formulario de crear un nuevo cliente falta colocar un campo donde se pueda especificar el código del cliente.

Para esta actividad el líder sera José Arturo y le enseñará como hizo para cumplir con este requerimiento a Cesar para poder a proceder a la entrega de conocimiento del mismo.

Cual quier pregunta técnica o duda pueden preguntarme a mí (David).

**Comment by alfiosaglimbeni** [comment]
### ISSUE
En el formulario de crear un nuevo cliente falta colocar un campo donde se pueda especificar el código del cliente.
Para esta actividad el líder sera José Arturo y le enseñará como hizo para cumplir con este requerimiento a Cesar para poder a proceder a la entrega de conocimiento del mismo.
Cual quier pregunta técnica o duda pueden preguntarme a mí (David).

### **PROBADO SATISFACTORIAMENTE**

**Comment by sofguar** [comment]
Se cierra porque esta en la rama de producción
