### ISSUE TITLE
No deben de cargar horas a futuro en horas no cargables

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#252]
Se debe limitar las horas las cuales el usuario puede seleccionar para cargar las horas, no debe de cargar horas a futuro solo desde la hora presente para atrás.

**Comment by dmolina101** [comment]
Ya los cambios los coloque en la rama principal y puedes hacer pull.

Que vamos a revisar en estos cambios?:

**1)** Que la **Fecha Desde** no sea superior o igual a la fecha con hora actual, es decir si la fecha actual es **07/09/2020 9:10 am**, la **Fecha Desde** debe tener como límite máximo para escoger **07/09/2020 8:30 am**, debido a que las horas para elegir son de intervalos de 30min y el intervalo de **9:00 am - 9:30** am aun no ha ocurrido.

**2)** Que la **Fecha Hasta** no sea menor o igual a la **Fecha Desde** ya que seria **0** tiempo trabajado, por lo menos la actividad debió tener un intervalo de **30min**.

**3)** Que la **Fecha Hasta** no sea superior a la fecha con hora actual, es lo mismo que el punto **1** pero con la diferencia que la **Fecha Desde** debe tener como máximo para elegir 30min menos que la **Fecha Hasta** para que se cumpla el intervalo mínimo de 30min por actividad, es decir si la fecha actual es **07/09/2020 9:10 am**, la **Fecha Desde** debe tener como límite máximo para escoger **07/09/2020 8:30 am** y la **Fecha Hasta** debe tener como límite máximo para escoger **07/09/2020 9:00 am**.

Cualquier duda o pregunta estamos a la orden @alfiosaglimbeni

**Comment by alfiosaglimbeni** [comment]
### LISTO
**_PROBADA DE FORMA SATISFACTORIA Y ACORDE A LA EXIGENCIA_**
**1) Que la Fecha Desde no sea superior o igual a la fecha con hora actual,** es decir si la fecha actual es 07/09/2020 9:10 am, la Fecha Desde debe tener como límite máximo para escoger 07/09/2020 8:30 am, debido a que las horas para elegir son de intervalos de 30min y el intervalo de 9:00 am - 9:30 am aun no ha ocurrido.

### LISTO
**_PROBADA DE FORMA SATISFACTORIA Y ACORDE A LA EXIGENCIA_**
**2) Que la Fecha Hasta no sea menor o igual a la Fecha Desde ya que seria 0 tiempo trabajado**, por lo menos la actividad debió tener un intervalo de 30min.

### LISTO
**_PROBADA DE FORMA SATISFACTORIA Y ACORDE A LA EXIGENCIA_**
**3) Que la Fecha Hasta no sea superior a la fecha con hora actual,** es lo mismo que el punto 1 pero con la diferencia que la Fecha Desde debe tener como máximo para elegir 30min menos que la Fecha Hasta para que se cumpla el intervalo mínimo de 30min por actividad, es decir si la fecha actual es 07/09/2020 9:10 am, la Fecha Desde debe tener como límite máximo para escoger 07/09/2020 8:30 am y la Fecha Hasta debe tener como límite máximo para escoger 07/09/2020 9:00 am.

**Comment by sofguar** [comment]
perfecto, vamos a colocarla para hacerle merge con la rama de producción

**Comment by sofguar** [comment]
Se cierra porque esta en la rama de producción
