### ISSUE TITLE
Validar que las horas cargadas no se solapen entre conceptos cargados HORAS NO CARGABLES

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#253]
Actualmente se puede cargar horas no cargables por un concepto X entre un rango de horas ya tomadas por otro concepto, la idea es arrojar una alerta donde indique que no puedes especificar ese rango de fecha porque ya parte o todo el rango ya esta tomado por otro concepto.

**Comment by sofguar** [comment]
Ya los cambios para probar este requerimiento están listos. 

**Que se tiene que probar?**

**1)** Cuando se registre una nueva **Hora No Cargable** valide que la fecha desde y hasta no este en un rango de fecha y hora usada por otra **Hora No Cargable** previamente cargada.

**2)** **1)** Cuando se este modificando una **Hora No Cargable** valide que la fecha desde y hasta no este en un rango de fecha y hora usada por otra **Hora No Cargable** previamente cargada.

Cualquier duda o pregunta estamos a la orden @alfiosaglimbeni

**Comment by alfiosaglimbeni** [comment]
### ISSUE
**Actualmente se puede cargar horas no cargables por un concepto X entre un rango de horas ya tomadas por otro concepto, la idea es arrojar una alerta donde indique que no puedes especificar ese rango de fecha porque ya parte o todo el rango ya esta tomado por otro concepto.**

**QUE SE PROBÓ**

**PRUEBA NO SUPERADA**
_1) Cuando se registre una nueva Hora No Cargable valide que la fecha desde y hasta no este en un rango de fecha y hora usada por otra Hora No Cargable previamente cargada._

### **SI FUNCIONÓ CORRECTAMENTE ESTO ES EXTRAÑO**
2) 1) Cuando se este modificando una Hora No Cargable valide que la fecha desde y hasta no este en un rango de fecha y hora usada por otra Hora No Cargable previamente cargada.

**Comment by sofguar** [comment]
Listo, se corrigió el problema del punto 1, por favor revisar

**Comment by alfiosaglimbeni** [comment]
Ahora si pasó la prueba no permite solapar horas no cargables

**Comment by sofguar** [comment]
Se cierra porque esta en la rama de producción
