### ISSUE TITLE
Probar configuración provista por el proveedor de correo para el envío del mismo

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#256]
El proveedor de corre mando las configuraciones necesarias para enviar correos desde la aplicación, hay que probar y colocarlo en funcionamiento.

**Comment by sofguar** [comment]
Muy buenos días Alfio, para configurar el envío de correo debemos editar el archivo que está en la raíz del proyecto encada ambiente tanto en calidad y producción. La parte que vas a editar es la siguiente que está sombreada:

![imagen](https://user-images.githubusercontent.com/55295214/93667203-fe105680-fa51-11ea-8ac5-c43535e8cea3.png)

Como me pasaste por correo vas a reemplazar los valores y quedaría así:

```
MAIL_DRIVER=smtp
MAIL_HOST=mail.crowe.com.ve
MAIL_PORT=587
MAIL_USERNAME=<< falta el correo o usuario quien envia el correo>>
MAIL_PASSWORD=<< falta la clave del correo o usuario quien envia el correo>>
MAIL_ENCRYPTION=tls
```
Como puedes ver faltan los valores de los atributos `MAIL_USERNAME `y `MAIL_PASSWORD`, los cuales son el usuario de quien envia el correo puedes usar el tuyo para probar y la clave del correo.

Luego de que edites el archivos puedes probar su funcionalidad tratando de recuperar tu contraseña en el formulario del login de crowe, si no llega la configuración esta mal, de igual manera debes esperar unos minutos o revisar la bandeja de spam si es el caso.

**Comment by alfiosaglimbeni** [comment]
**CREDENCIALES USADAS**


MAIL_USERNAME 
soporte.carent@crowe.com.ve
 MAIL_PASSWORD
C@r3nt*


**CAMBIO REALIZADO EN EL ARCHIVO .ENV**


MAIL_DRIVER=smtp
MAIL_HOST=mail.crowe.com.ve
MAIL_PORT=587
MAIL_USERNAME=soporte.carent@crowe.com.ve
MAIL_PASSWORD=C@r3nt*
MAIL_ENCRYPTION=tls


**IMAGEN DEL ERROR GENERADO**


![image](https://user-images.githubusercontent.com/22016865/96943480-47672200-14a6-11eb-97d9-e03d921c766a.png)

**Comment by sofguar** [comment]
Ok prueba con esta configuración en el **.env**, es la que se usa para probar con un servidor de correo fake, si funciona tienes que revisar que parámetro esta mal con los de Crowe.

```
MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=147d7ec35f4c24
MAIL_PASSWORD=8bb111016dc2fe
MAIL_ENCRYPTION=tls
```

**Comment by djcesar28** [comment]
Configuración Correo Electronico de Recuperación
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=no.responder.carent@gmail.com
MAIL_PASSWORD=**C@r3nt**
MAIL_ENCRYPTION=tls

**Comment by sofguar** [comment]
Requerimiento funcionando en producción
