### ISSUE TITLE
Nuevo Campo en el Módulo de Facturación

### ISSUE THREAD

**Issue by sergiofma** [sofguar/carent#258]
David, en el módulo de facturación debemos agregar un campo que se llame **Otros Gastos** que resta al ingresos total del proyecto y tiene que ver con las comisiones que terceros nos cobran y afectan el proyectos.

**Comment by dmolina101** [comment]
Cuando usted dice otro campo quiere decir tipo de concepto? es decir que lo agregue como los tipos de concepto **Gastos No Reembolsables**?

**Comment by sofguar** [comment]
Requerimiento culminado.

¿Qué probar?

1) Que la bandeja de entrada de ingresos/gastos
2) Que puedas asociar una factura y gasto al proyecto
3) Que se pueda eliminar una factura o gasto del proyecto
4) Que se pueda modificar los datos de una factura o gasto cargados al proyecto. El nº de factura no se puede cambiar, si se desea cambiar se debe anular
