### ISSUE TITLE
Colocar Fecha Desde y Fecha Hasta en el filtro de busqueda de las horas no cargables

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#261]
Como ya se restringen las horas desde y hasta para no ser empleadas en dos conceptos a la vez por usuario es necesario filtrar dichos conceptos o horas no cargables por fechas para que el usuario pueda corroborar que otra hora no cargable esta empleando dichas fechas.

**Comment by sofguar** [comment]
Ya el requerimiento esta listo en su fase de desarrollo.

Que se tiene que probar?

**1)** Que el filtro funcione con un rango de **Fecha Desde - Hasta** y traiga resultados de existir.

**2)** Que si solo se indique la **Fecha Desde** solo haga un búsqueda exacta para esa fecha y hora

**Comment by alfiosaglimbeni** [comment]
### ISSUE
**Como ya se restringen las horas desde y hasta para no ser empleadas en dos conceptos a la vez por usuario es necesario filtrar dichos conceptos o horas no cargables por fechas para que el usuario pueda corroborar que otra hora no cargable esta empleando dichas fechas.**

**Que se tiene que probar?**

**Probado exitosamente**
_1) Que el filtro funcione con un rango de Fecha Desde - Hasta y traiga resultados de existir._
**Probado exitosamente**
_2) Que si solo se indique la Fecha Desde solo haga un búsqueda exacta para esa fecha y hora_

**Comment by sofguar** [comment]
Se cierra porque ya esta en la rama de producción
