### ISSUE TITLE
Subir la cantidad de registros por filtro por lo menos 50 por página

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#267]
Se debe aumentar el número de registros mostrado por filtro, por lo menos 50 por página

**Comment by sofguar** [comment]
Listo los cambios, se subió la paginación a 50 resultados por página en las bandejas de horas no cargables y proyectos creados.

Que probar?

**1)** Hay que verificar que en verdad muestren 50 resultados por página

**Comment by alfiosaglimbeni** [comment]
El día de hoy 10092020 se reviso y se verifico que se pueden visualizar 50 registro por página
por Q&A se puede cerrar está solicitud

**Comment by sofguar** [comment]
se cierra porque ya esta en la rama de producción
