### ISSUE TITLE
Permitir eliminar horas cargables al usuario que las generó

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#271]
Actualmente no hay una opción que permita modificar o eliminar una hora cargable si se equivocó el usuario, como no es difícil cagar solo hay que habilitarle una opción de eliminar para que vuelva a cargar.

**Comment by serodriz** [comment]
Listos los cambios.

1- Al entrar en la ventana de horas cargables, en el cuadro de las horas debería estar habilitada la opción de eliminar a todos los usuarios

2- Al hacer clic para cargar horas este se debería bloquear hasta que se complete el proceso.

3- Al tratar de cargar una fecha futura, le debería mostrara un mensaje indicando: Elegir una fue valida.

**Comment by alfiosaglimbeni** [comment]
### ISSUE

**Actualmente no hay una opción que permita modificar o eliminar una hora cargable si se equivocó el usuario, como no es difícil cagar solo hay que habilitarle una opción de eliminar para que vuelva a cargar.**
**COMPROBADO CON OBSERVACIÓN PARA MEJORA** _a satisfacción, si ´permite elimina el registro o registros de las horas cargadas por el usuario_

**COMPROBADO Y APROBADO**
1- Al entrar en la ventana de horas cargables, en el cuadro de las horas debería estar habilitada la opción de eliminar a todos los usuarios

**COMPROBADO Y APROBADO**
2- Al hacer clic para cargar horas este se debería bloquear hasta que se complete el proceso.

**COMPROBADO Y APROBADO**
### OBSERVACIÓN PARA MEJORA:
**_El sistema arroja un mensaje indicando "Introducir una fecha válida" ese mensaje debería ser cambiado a "A intentado introducir una actividad en una fecha a futuros acción no permitida" o algo por el estilo_**
3- Al tratar de cargar una fecha futura, le debería mostrara un mensaje indicando: Elegir una fue valida.

**Comment by serodriz** [comment]
Corrección del mensaje que indicaba por el sugerido por alfio

**Comment by sofguar** [comment]
Se cierra porque ya esta en la rama de producción
