### ISSUE TITLE
Amarrar que solo los gerentes asignados por divisiones al crear el proyecto puedan asignar horas y participantes

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#273]
Para esta tarea se debe esperar culminar la **Issues #272** . Una vez que los gerentes asignados por division sean indicados a la hora de crear el proyecto se debe de amarran en la bandeja de proyecto de las **Horas Cargables** solo dichos gerentes puedan ver sus proyectos asignados y no lo de los demas y solo ellos pueden asignar horas y personal al proyecto.

**Comment by sofguar** [comment]
Listo @serodriz  ya puedes empezar con esta tarea ya que la issues por la cual prelaba esta lista

**Comment by serodriz** [comment]
Listo los cambios de amarrar a los gerentes y el socio asignados al crear el proyecto.

Que probar?

1- Con un usuario que sea socio y gerente encargado de proyectos al acceder al menú asig.Personal/HorasCargadas debería mostrase la siguiente ventana
![image](https://user-images.githubusercontent.com/59027265/94200485-7cbd2780-fe88-11ea-8c41-1c246a48e31e.png)

2- Con un usuario que sea gerente de la división del proyectos al acceder al menú asig.Personal/HorasCargadas debería mostrase la siguiente ventana
![image](https://user-images.githubusercontent.com/59027265/94202793-55685980-fe8c-11ea-9cd8-a062b0a42ce9.png)

3- Con un usuario al ser asignado a un proyecto por los gerentes o el socio al acceder al menú asig.Personal/HorasCargadas debería mostrase la siguiente ventana
![image](https://user-images.githubusercontent.com/59027265/94202993-b09a4c00-fe8c-11ea-976f-a9b6a686b113.png)

4- Probar cada uno de los botones y comprobar si están funcionando

nota: Como se puede observar ahora la asignación del personal y las horas las realizara el socio y los gerentes encargado de cada proyecto.

**Comment by sofguar** [comment]
Perfecto, voy a proceder a subir los cambios a la rama de Calidad para que @alfiosaglimbeni pueda probarlos

**Comment by alfiosaglimbeni** [comment]
### PRUEBA REALIZADA:
**USUARIO** 11265 GUSTAVO PUCHI GERENTE
**CLIENTE**: BANCO ACTIVO BANCO UNIVERSAL
**PROYECTO** PENTESTING

- Se seleccionó el comando Asig. Personal / Horas Cargables. del menú PROYECTO
- Se visualizó un listado de proyectos asignados a la División Auditoría TI y al Gerente Gustavo Puchi.
- Se hizo clic en el icono de Asignar del proyecto indicado anteriormente.
- Se asigno las horas al personal de la división
- Con el mismo usuario (11265) se realizo una serie de carga horaria en este proyecto.
- Se uso otro usuario (11376) de la misma división para una carga adicional de horas en el proyecto 
- Se volvio a hacer login con el usuario 11265 para visualizar la carga total de hora resultando satisfactoria la actividad

### PRUEBA SUPERADA

**Comment by sofguar** [comment]
Perfecto, se procede a unir este cambio a la rama de producción
