### ISSUE TITLE
Actualizar código fuente del formulario de Crear Nuevo Usuario

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#276]
Se requiere actualizar código fuente del formulario de crear un nuevo usuario empleado bootstrap-vue; se debe de guiar por el formulario de crear proyecto el cual ya ha sido migrado bajo esa metodología.

**Comment by sofguar** [comment]
Bueno ya revise los cambios y si como tu lo indicabas te faltan algunas cosas que cambiar; la idea es cambiar todas las etiquetas del **nuevoUsuario.blade.php** a como esta el **nuevoProyecto.blade.php**, si te fijas por ejemplo en el blade del nuevo usuario después de la linea 21 en el código `<menu-principal v-cloak></menu-principal>` hay una linea con el código `<div class="row align-items-center justify-content-center wrapper-forms" v-cloak>`, con el cambio a como esta el blade nuevo proyecto quedaría `<b-row align-h="center" align-v="center" class="wrapper-forms" v-cloak>`.

Como te indique anteriormente trata de cambiar todas las que detectes que puedas cambiar, obvio no espero que lo hagas perfecto pero la idea es que vayas aprendiendo la nueva migración y como van a quedar los formularios con la nueva metodología con **bootstrap-vue**.

Intenta nuevamente cambiar lo que tu consideres que puedas cambiar y lo volvemos a revisar hasta que este al 100% ok? tranquilo, la idea es que aprendas.

De igual manera te indico que con la nueva migración vienen otros cambios en el js también, por ejemplo en el blade de nuevo usuario no esta la variable **form.mostrar**, el cual es una variable que si esta en el blade nuevo proyecto. Con esta variable controlaremos cuando mostrar el formulario; no te preocupes por ahora, primero trata de cambiar las etiquetas y luego cambiamos el js.

Cualquier cosa me preguntas

**Comment by djcesar28** [comment]
perfecto

**Comment by sofguar** [comment]
Buenos Cesar, efectivamente hay un error como me indicaste, la pantalla te sale en blanco y te explicare el ¿por que?. EL código actual del formulario **"Nuevo Usuario"** esta realizado con VueJS y Bootstrap pero de manera separada, es decir **VueJS** estaría en el **js** y **Bootstrap** en el **blade**. Con la migración se intenta integrarlo los dos con **[Bootstrap-vue](https://bootstrap-vue.org/docs/components)** para tener un mejor rendimiento ya que con esta librería ayudaría a utilizar al 100% las bondades de **VueJS** a **Bootstrap** que es el encargado del diseño.

Ahora bien cuando se migra como te fijaste cambia el blade en la forma de diseñar los campos y de igualmaner muy seguramente también el js, pero es solo a nivel de estructura o quizás un poco en lo lógico. Dicho esto te mostraré lo que esta pasando actualmente y trataré de hacer el primer campo para que te guíes:

1) La pantalla en blanco es porque ocurrió un error, si abrimos la consola te lo mostrará:

![1](https://user-images.githubusercontent.com/55295214/93348268-fe1b1700-f803-11ea-8d1c-e13e843deeb1.jpg)

Ese error en este caso quiere decir que estamos usando unas propiedades a la hora de renderizar (Mostrar por pantalla) que no están definidas en el VueJS. Veamos como está el código del blade:

![2](https://user-images.githubusercontent.com/55295214/93348589-679b2580-f804-11ea-9ff6-008796eb197a.jpg)

La parte sombreada es el campo que intentaste migrar con el nuevo código. Los atributos del campo que comience con dos puntos **:** quiere decir que están de alguna manera enlazados a la estructura del **VueJS** definida en su js, es decir, estan buscando su valor en el js y en este caso al parecer no esta o no al menos de la misma manera que lo esta intentando buscar.

Veamos el JS:

![3](https://user-images.githubusercontent.com/55295214/93349026-f8720100-f804-11ea-829e-680cf85b35a1.jpg)

En la parte sombreada veras la estructura del **form**, si te fijas esta el **form** y directamente los atributos de los campos, es decir **form.nombre1.disabled** por ejemplo y así sucesivamente por cada campo, pero el campo esta buscando **form.camposAtributos.nombre1.disabled** para que no te de error tendríamos que cambiar la estructura del form para que el campo pueda encontrar dicho valor quedando así:

![4](https://user-images.githubusercontent.com/55295214/93350346-8a2e3e00-f806-11ea-96a3-0d2168539b37.jpg)

Si te fijas en la parte sombreada veras como quería la nueva estructura del **form** con el campo **nombre1**.

Ahora bien debemos eliminar la estructura del campo viejo:

![5](https://user-images.githubusercontent.com/55295214/93350888-15a7cf00-f807-11ea-89ca-7e286a19922d.jpg)

Quedando así:

![6](https://user-images.githubusercontent.com/55295214/93351197-6ae3e080-f807-11ea-93b9-7b1d05971a6f.jpg)

Se elimina para ir limpiando el código y lo iras haciendo a medidas que vas avanzando por los campos. Ahora bien falta agregarle la validación al campo para que no te de otro error. ¿Donde se llama la validación?:

![7](https://user-images.githubusercontent.com/55295214/93351819-260c7980-f808-11ea-87e2-d0674820acb1.jpg)

En el blade como veras en la parte sombreada está en el atributo **v-model**. **v-model** es el atributo que contendrá el valor actual del campo, no te preocupes a medida que avanza entenderás su funcionamiento al 100%.

Como puedes ver **v-model** tiene un valor de **$v.form.campos.nombre1.$model**, eso quiere decir que el esta buscando la estructura **form.campos.nombre1**. Veamos que necesitamos:

![8](https://user-images.githubusercontent.com/55295214/93351994-5ce28f80-f808-11ea-9559-70b6f112605a.jpg)

Como puedes ver en la parte sombreada, debemos crear la estructura **form.campos.nombre1** con valor en **null** en este caso para que el atributo **v-model** lo pueda encontrar, ademas debemos incluir la estructura **validations**:

![9](https://user-images.githubusercontent.com/55295214/93352210-99ae8680-f808-11ea-8dc2-1d838b54e55a.jpg)

En la estructura **validations** deberás colocar los campos para que puedan ser validados (Faltan otras cositas pero lo veremos cuando te tropieces con la acción de guardar).

Para que la validación funcione debemos llamar a su librería correspondiente así:

![10](https://user-images.githubusercontent.com/55295214/93352550-f5790f80-f808-11ea-8cd8-19c9034dbe5c.jpg)

Como lo ves en la parte sombreada sería como se incluye la librería para la validación, después que vayamos avanzando vamos a ir colocando otras y eliminando viejas, por ahora pienso es todo puedes ir avanzando en los demás campos y si surge otro error o te trancas en algo se te explica como avanzar.

La pantalla con los cambios que ya están en tu rama y puedes hacer el **pull** quedaría así:

![11](https://user-images.githubusercontent.com/55295214/93352887-5274c580-f809-11ea-92a0-7072a3b29737.jpg)

De igual manera ve viendo el formulario Nuevo Proyecto, de allí me guíe yo.

**Have fun!**

**Comment by sofguar** [comment]
Bueno @djcesar28 con respecto al error en el combo de tipo de documento

![1](https://user-images.githubusercontent.com/55295214/93607638-985f9400-f997-11ea-8209-22e1302963e8.jpg)

Como ya sabes esta dando como opciones **null** y te voy a explicar el ¿por qué?. Como te había mencionado antes muy seguramente la estructura del **js** puede cambiar porque ya el **VueJS** esta 100% ligado al **blade** a través de la librería **bootstrap-vue**; ahora bien vamos analizar como está y como debería de ser:

Veamos el blade donde esta dando null:

![2](https://user-images.githubusercontent.com/55295214/93608327-7c102700-f998-11ea-8b0e-ec74422a2d72.jpg)

En la imagen anterior está la estructura como la colocaste según la nueva migración. Ahora bien si te fijas las opciones están contenidas en el atributo` :options="comboTipoDocumento`

![3](https://user-images.githubusercontent.com/55295214/93608624-d1e4cf00-f998-11ea-96d4-1148963f3149.jpg)

Como ves en la imagen el atributo `:options` esta llamando la variable `comboTipoDocumento` el cual es llenada o toma su valor en la siguiente parte del código del JS en el ciclo de vida del VueJS **beforeCreate** como veras a continuación:

![4](https://user-images.githubusercontent.com/55295214/93609092-6bac7c00-f999-11ea-95df-e45fa7e8728c.jpg)

Como ves la variable `comboTipoDocumento` se le asigna el valor proveniente del ajax `response.data.tipoDocumentos`. Veamos si viene con valores desde el ajax:

![5](https://user-images.githubusercontent.com/55295214/93609741-35bbc780-f99a-11ea-896d-f7b37902c9df.jpg)

Perfecto, viene con datos como pudiste ver, pero ¿por qué no me muestra los resultados y me salen en null?. Chequeastes el formulario de crear un nuevo proyecto como se te recomendó? veamos:

Vamos a ver como esta el formulario de crear un nuevo proyecto:

![6](https://user-images.githubusercontent.com/55295214/93610101-a7941100-f99a-11ea-9c8f-d7dfd98de237.jpg)

Tomemos el campo **Estatus** como base, vamos a ver su estructura en el blade:

![7](https://user-images.githubusercontent.com/55295214/93610692-62241380-f99b-11ea-8b4e-ab450fcb8c77.jpg)

Como pude observar tienes una estructura bajo la nueva filosofía de la migración, bien, ahora veamos el js:

![8](https://user-images.githubusercontent.com/55295214/93611005-bcbd6f80-f99b-11ea-9149-b1824391a113.jpg)

Como puedes ver no se asigna directamente los valores como lo haces en el formulario de nuevo usuario, aquí hacemos un bucle con el **forEach**, entonces tu deberías de recorrer dentro de un **forEach** **comboTipoDocumento** obtener los valores por cada registro y asignárselos a `text `y `value `como ves en la imagen para que te muestre los resultados y no null.

Para más información y manejar este tipo de campos dirigete al siguiente enlace:

[Bootstrap-vue form-select](https://bootstrap-vue.org/docs/components/form-select)

De ese enlace me guíe yo, cualquier duda o pregunta me avisas.

**Comment by sofguar** [comment]
Se cierra porque no se culmino la actividad por parte de los responsables
