### ISSUE TITLE
Actualizar el formulario de modificar proyecto

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#296]
Se requiere migrar y agregar los nuevos campos que se implementaron en el formulario de crear proyecto al formulario de modificar proyecto.

**Comment by sofguar** [comment]
El requerimiento esta listo, para probar se requiere:

1) Crea un nuevo proyecto y luego trata de editarlo; prueba editando todos los campos.
2) Trata de editar un proyecto que ya ha sido creado con anterioridad, quizás no tengan gerentes por división, recuerda que este cambio fue posterior.

**Comment by alfiosaglimbeni** [comment]
### PRUEBAS REALIZADAS
### 1) Crea un nuevo proyecto y luego trata de editarlo; prueba editando todos los campos.
### Datos usados:
Para esta prueba se uso el usuario 0001, se creo un proyecto usando el cliente ADMINISTRADORA CCCT, el proyecto se denominó "auditoría de vulnerabilidad" el socio es SAMUEL ALEJANDRO MARQUEZ TOVAR y el gerente es GUSTAVO ADOLFO PUCHI MEDINA la moneda usada es US$ y el monto 1500, la divisiones Auditoría TI, con una cantidad de horas de 150.
**LA CREACIÓN DEL PROYECTO FUE COMPLETADA EXITOSAMENTE**
**EDICIÓN DEL PROYECTO RECIEN CREADO**
**_CAMBIOS REALIZADOS_**
1. En el campo Descripción se cambio con AUDITORíA DE VULNERABILIDAD DICIEMBRE 2020
2. Se cambio el cliente por ADMINISTRADORA CENTRO FINANCIERO LATINO, C.A.
3. Se cambio la fecha de contratación al 07/09/2020 (originalmente era 14/09/2020
4. Se cambio el socio a SERGIO FREDDYS MÁRQUEZ TOVAR
5. Se cambio de Gerente a EMILIO JOSE LEON FARIAS
6. Se cambio la moneda a Euro
7. Se cambio el monto a 2.000
8. Se cambio al responsable a Alfio Saglimbeni
9. Se cambio la cantidad de horas a 200
10. Se hizo clic en ele botón Modificar proyecto
_Apareció el mensaje_ **Proyecto actualizado con éxito**
**_LOS CAMBIOS FUERON SATISFACTORIOS_**

### 2) Trata de editar un proyecto que ya ha sido creado con anterioridad, quizás no tengan gerentes por división, recuerda que este cambio fue posterior.

Se uso para este proyecto "AUDITORIA A LOS ESTADOS FINANCIEROS AL 30 DE JUNIO DE 2020" de 244 horas de fecha de contratación 01/07/2020 del cliente VALORALTA CASA DE BOLSA con el socio SAMUEL ALEJANDRO MARQUEZ TOVAR y la gerente YESENIA BEATRIZ MARTINEZ GALLARDO y no tiene gerente asignado para la división.

**QUE SE PROBO:**

- Agregar al responsable LUZ FONSECA
- Se hizo clic en el botón Modificar
- Apareció el mensaje "Proyecto actualizado con éxito."

### PRUEBA SUPERADA

**Comment by alfiosaglimbeni** [comment]
### SEGUNDA PRUEBA DEL PUNTO 2
**2) Trata de editar un proyecto que ya ha sido creado con anterioridad, quizás no tengan gerentes por división, recuerda que este cambio fue posterior.**
**_DATOS USADOS:_**
**AUDITORIA A LOS ESTADOS FINANCIEROS AL 30 DE JUNIO DE 2020 horas contratadas 2460, fecha de contratación 01/07/2020, cliente BANCO AGRICOLA DE VENEZUELA socio NELSON JOSE MARCANO gerente YESENIA BEATRIZ MARTINEZ GALLARDO, no posee gerentes asociados a las divisiones asignadas**
**MODIFICACIONES REALIZADAS:**
- En el campo Descripción NO HUBO CAMBIOS
- En el campo cliente NO HUBO CAMBIOS
- Se cambio la fecha de contratación al 07/09/2020 (originalmente era 01/09/2020
- Se cambio el socio a SERGIO FREDDYS MÁRQUEZ TOVAR originalmente Nelsón Marcano
- Se cambio de Gerente a LUZ AMANDA FONSECA GARCIA originalmente YESENIA BEATRIZ MARTINEZ GALLARDO
- Se cambio la moneda a Euro originalmente BsS 
- Se cambio el monto a 20.000 originalmente 2.600.000.000,00
- Se mantuvieron las CINCO divisiones originales y la cantidad de horas
- Se agregaron los siguientes gerentes que antes no se habían asignados
- Auditoría Externa: Oliver Paez
- Auditoría TI: Gustavo Puchi
- Asesoría Tributaria: Eliana Ponce
- Business and Process Consulting: Angela Aranea.
- Legal: **NO HAY GERENTE ASOCIADO A ESTA DIVISIÓN**
- Se hizo clic en el botón Modificar proyecto
- PROYECTO MODIFICADO CON ÉXITO

### PRUEBA SUPERADA

**Comment by sofguar** [comment]
Perfecto, procedo a unir las ramas de calidad y producción para estos cambios
