### ISSUE TITLE
Validar que no cambie el tipo de moneda en el proyecto si ya existe una facturación del mismo

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#303]
Si el proyecto ya posee facturaciones, no debe de poderse cambiar el tipo de moneda del proyecto para evitar conflictos.

¿Qué opinas sobre esta validación @sergiofma ?

**Comment by sergiofma** [comment]
No

**Comment by sofguar** [comment]
Listo, para probar puedes probar el siguiente escenario:

1) Edita el proyecto y cambiale el tipo de monda
2) Emitele al proyecto una factura
3) Trata de modificar el proyecto cambiandole el tipo de moneda

**Comment by alfiosaglimbeni** [comment]
Se generó un proyecto denominado PRUEBA CAMBIO TIPO MONEDA por un total de horas de 500 contratado el  01/12/2020 asignado al cliente BANCO ACTIVO BANCO UNIVERSAL y el socio es SAMUEL ALEJANDRO MARQUEZ TOVAR, con el gerente OLIVER JOSE PAEZ RANGEL. se usó la divisa US$ y un monto de US$5.000,00.
Luego se ingreso una 1ra factura por US$ 2.500,00.
Se procedió a modificarl el proyecto cambiando la divisa de US$ a Bs y lo permitió

**Comment by sofguar** [comment]
Cambio probado y en rama de producción
