### ISSUE TITLE
Enviar una notificación de correo al usuario quien se le a pruebe sus horas no cargables

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#307]
Hay que enviar un correo una vez cambie de estatus al usuario que cargo sus horas no cargables ya sea por aprobación o no por su supervisor.

Para empezar esta tarea se necesita probar las configuraciones del correo previstas en el issues #256

**Comment by sofguar** [comment]
Requerimiento listo, que probar?

**1)** Cuando un empleado registre las horas no cargables llegue un correo de notificación a sus supervisores vía correo.
**2)** Cuando un supervisor cambia el estatus de una hora no cargable de un empleado, el sistema debe notificarle al empleado qvia correo dicho cambio.

**Comment by alfiosaglimbeni** [comment]
Se realizó la prueba de forma satisfactoria
![imagen](https://user-images.githubusercontent.com/22016865/100293952-fdf96f00-2f4a-11eb-9488-73afa95cc8ab.png)

**Comment by sofguar** [comment]
Ya el issues esta en producción
