### ISSUE TITLE
Mejorar la opción de asignar permisos de los menus sobre los usuarios

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#311]
Actualmente la pantalla para asignar permisos a los usuarios está así:

![imagen](https://user-images.githubusercontent.com/55295214/94555524-b2b43000-0229-11eb-9ed9-039288df95d3.png)

El problema que veo en esta pantalla es que no se ajusta al 100% a la filosofía de como actualmente el sistema por debajo en realidad asigna los permisos a los usuario;.

Te mostraré como está creada la base de datos y me explicaré:

![imagen](https://user-images.githubusercontent.com/55295214/94556287-d75cd780-022a-11eb-86a7-cb85143a66be.png)

Como puedes ver en la tabla **tbl_menu_usuario** hay un campo **id_usuario** donde se asigna el id del usuario el cual tendrá el menú asociado, un campo **id_menu** donde se indicará el id del menú para asociarselo al usuario y otros 4 campos **C**, **R**, **U** y **D** donde se indican que puede hacer el usuario dentro de ese menú si es **C**reate (crear), **R**ead (leer), **U**pdate (actualizar) ó **D**elete (Eliminar). 

**Nota:** Cuando se le indica Delete, no ajuro hay que eliminar quizas con un Update a un estatus que el usuario no pueda ver basta todo depende del caso si es mejor eliminar o actualizar claro dejando para cualquiera de los dos casos una bitácora de la acción.

Ahora bien se que tu estas consiente de todo lo que dije con anterioridad ya que tu hicistes esa parte del sistema pero creo que la pantalla no se ajusta al 100% por lo siguiente:

**1)** Como vistes en la tabla **tbl_menu_usuario** se agrega menú por menú a un usuario, por lo que la pantalla debería de desglosar por modulo independientemente del cargo o división todos los módulos con sus menús y acciones que se les puedes asignar. Así evitamos inconvenientes a la hora de asignar un menú a un usuario que en **TEORÍA DEBERÍA** ó **NO DEBERÍA** de poseer. Dejemos que la persona en cargada de asignar permisos tenga esa potestad no encasillarlo porque si por alguna eventualidad se le desea asignar un menú de facturación a uno de TI por x motivo lo puedan hacer.

**Nota:** Esta tarea no es prioritaria pero si necesaria, por lo que si surge otra de mayor importancia se puede dejar en stand by

**2)** También se debería de colocar 4 checkbox o como tu mejor veas la manera de indicar las 4 acciones de crear, leer, actualizar o eliminar. De igual manera en las pantallas como venimos haciendo en el controlador siempre se evalúa si el tiene los permisos correspondientes.

**3)** Dejarlo como tenias desglosado por módulos.

Por ahora es todo, si tienes alguna duda o pregunta házmela saber por aquí o por whatsapp, de todas maneras a medida que vayas avanzando vemos los cambios y corregimos o mejoramos lo que tengamos que mejorar, la idea es hacerlo lo más ergonómico posible para el usuario y que no dependa de nosotros como programadores.

**Comment by serodriz** [comment]
Listo los cambios de mejora de la asignación de menus.

hacer antes:
1- Agregar 4 nuevos campos en la tabla tbl_menus
1.1- Campos a agregar despues de orden C R U D todos tipo boolean
1.2- Asignarles los valores correspondiste a cada uno de los datos ya registrado como se muestra a continuación

![image](https://user-images.githubusercontent.com/59027265/97096974-220f1b00-1642-11eb-9eb5-afb09d723322.png)


Una vez realizado los ajuste en la BD deberá revisar la asignación de menús que se encuentra en el menús de consultar usuario.
Al abrir la modal de asignar debería mostrarse de la siguiente manera.

![image](https://user-images.githubusercontent.com/59027265/97067015-5a9dee80-1587-11eb-86a9-7d49609c88b6.png)

Comprobar que la asignación de menús funciona correctamente.

**Comment by sofguar** [comment]
Perfecto!

**Comment by alfiosaglimbeni** [comment]
1- Agregar 4 nuevos campos en la tabla tbl_menus **listo**
1.1- Campos a agregar despues de orden C R U D todos tipo boolean **listo**
1.2- Asignarles los valores correspondiste a cada uno de los datos ya registrado como se muestra a continuación **listo**
### Ahora el issue 322

**Comment by sofguar** [comment]
Requerimiento culminado, ya esta en la rama de producción y funcionando
