### ISSUE TITLE
Colocar el formulario de registrar nueva factura en una ventana modal

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#312]
Hay que mover el formulario donde se registran las nuevas facturas al proyecto a una ventana modal para hacerlo mas ergonómico y así darle mucha más visibilidad a las facturas ya cargadas.

Pantalla actual:
![imagen](https://user-images.githubusercontent.com/55295214/94674211-d76ddd80-02e5-11eb-9bf5-5d4d670f66f0.png)

**Comment by sofguar** [comment]
El requerimiento esta listo.

**¿Qué probar?**

**1)** Verificar que el formulario que se muestra en la imagen en el planteamiento del problema se muestre e un popup o un ventana modal.

**Comment by alfiosaglimbeni** [comment]
**Se ingresó al módulo de facturación se muestra la siguiente ventana**

![image](https://user-images.githubusercontent.com/22016865/95925043-d5e0f280-0d86-11eb-896e-21334fd07bbe.png)

**se hizo clic en el botón "Agreagar Factura" y apareció la siguiente ventana emergente**

![image](https://user-images.githubusercontent.com/22016865/95925165-1b052480-0d87-11eb-8e48-581856b62f44.png)

### Se ingresaron datos y los mismos registrados exítosamente
