### ISSUE TITLE
Colocar un campo de horas y montos adicionales en el formulario de editar proyecto

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#314]
Hay que colocar un campo donde se especifica las horas adicionales dentro del formulario de editar proyecto.

**Comment by sofguar** [comment]
Hay cambios en la Base de Datos que hay que hacer, el primero consta de:

1) Crear una tabla llamada **tbl_proy_monto_adicional**, que tiene como campos:

- id Int auto increment
- id_proyecto Int
- monto decimal (25,2)
- fecha date
- id_estatus Int

2) Crear la clave foránea que a punta a la tabla **tbl_proyecto**:

- ALTER TABLE tbl_proy_monto_adicional ADD FOREIGN KEY (id_proyecto) REFERENCES tbl_proyecto(id) ON DELETE RESTRICT ON UPDATE RESTRICT; 

3) Insertar los estatus en la tabla **tbl_estatus** con el siguiente SQLs:

- INSERT INTO tbl_estatus (id, tabla, valor, descripcion) VALUES (NULL, 'tbl_proy_monto_adicional', '1', 'Activo'), (NULL, 'tbl_proy_monto_adicional', '2', 'Inactivo');

4) Crear una tabla llamada **tbl_proy_div_horas_adic** que tiene como campos:

- id Int auto increment
- id_proy_div Int
- horas Int
- fecha date
- id_estatus Int

5) Crear una clave foránea que apunte a la tabla **tbl_proyecto_divisiones**

- ALTER TABLE tbl_proy_div_horas_adic ADD FOREIGN KEY (id_proy_div) REFERENCES tbl_proyecto_divisiones(id) ON DELETE RESTRICT ON UPDATE RESTRICT; 

6) Insertar los estatus en la tabla **tbl_estatus** con el siguiente SQL:

- INSERT INTO tbl_estatus (id, tabla, valor, descripcion) VALUES (NULL, 'tbl_proy_div_horas_adic', '1', 'activo'), (NULL, 'tbl_proy_div_horas_adic', '2', 'inactivo');

**Comment by alfiosaglimbeni** [comment]
El d{ia de hoy se realizaron los cambios en el ambiente de Calidad

**Comment by sofguar** [comment]
Cambio probado y en rama de producción
