### ISSUE TITLE
Dar la posibilidad en las horas cargables de cargas las horas en franciones de media hora

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#315]
Hay que dar la posibilidad en el formulario de las horas cargables, de cargas fracciones de media hora, actualemente solo se puede hacer con número enteros, ahora se requiere hacerse como las horas no cargables donde se pueden elegir fracciones de media hora.

**Comment by serodriz** [comment]
Listo los cambios de amarrar a los gerentes y el socio asignados al crear el proyecto.

Nota: hay que modificar el campo de la tabla tbl_horas_cargables

Que probar?

1- que el input de horas trabajas se ve como se aprecia en la imagen y el input horas asignadas se muestre como HH:MM

![image](https://user-images.githubusercontent.com/59027265/94970516-d1891f80-04d2-11eb-8101-dca73523dff0.png)

2- Cargar unas horas y comprobar que el input de horas cargadas, tenga el formato de HH:MM

**Comment by serodriz** [comment]
Aplicar la siguiente  sentencia en el phpmyadmin en la tabla tbl_horas_cargables

UPDATE tbl_horas_cargables SET horas_trabajadas = CONCAT('0', horas_trabajadas, ':00');

![image](https://user-images.githubusercontent.com/59027265/95084747-500cd980-06ec-11eb-8d9c-82c76c67462b.png)

y convertirá todos los datos a

![image](https://user-images.githubusercontent.com/59027265/95084911-88141c80-06ec-11eb-97d7-f549f35fa8db.png)

**Comment by sofguar** [comment]
Perfecto gracias José

**Comment by alfiosaglimbeni** [comment]
**Se realizaron dos pruebaq de carga de hora fraccionada en Calidad ambas fueron satisfactorias**
![image](https://user-images.githubusercontent.com/22016865/95664387-60222000-0b15-11eb-9721-585657763dbf.png)

**Comment by sofguar** [comment]
@alfiosaglimbeni despues de ejecutar la consulta que indico @serodriz la cual es:

`UPDATE tbl_horas_cargables SET horas_trabajadas = CONCAT('0', horas_trabajadas, ':00');`

Debes cambiar el tipo de datos del campo **horas_trabajadas** de **VARCHAR** a **TIME**
