### ISSUE TITLE
Modificación del formulario Crear Cliente y Modificar Cliente

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#317]
Se requiere modificar la manera en que se registra la dirección de los nuevos clientes asi como en su modificación debido a que actualmente solo se permite ingresar direcciones nacionales y hay casos en donde se puede agregar o registrar un cliente internacional.

**1)** Solo re requerirá dos campos, uno donde se indique el país a través de un combo y un campo de textarea para que indique todo lo demás como código postal, calle o avenida, edif, etc.
**2)** Como son muchos países puedes utilizar esta librería **vue-multiselect** que se emplea en el formulario **Horas No Cargables > Cargar**; puedes ver como se emplea en el js formHorasNoCargables.js y en el blade formHorasNoCargables.blade.php.
**3)** Como solo se necesita el país y la dirección escrita en un campo de textarea debes de eliminar los campos de Estado, Municipio, Parroquia y Ciudad.
**4)** El campo de textarea debe llevar como título **Dirección**
**5)** Se deben de eliminar la **tbl_ciudades**, ya que actualmente no se emplea en ninguna parte del formulario, puedes constatar eso de igual manera.

Por ahora es todo, cualquier duda o pregunta házmela saber.

**Comment by serodriz** [comment]
Listo los cambios de amarrar a los gerentes y el socio asignados al crear el proyecto.

hacer antes:

1- modificar la tabla tbl_cliente
   1.1- Eliminar los campos, id_parroquia, ciudad_fiscal, avenida_calle_fiscal, edificio_quinta_fiscal, piso_fiscal,numero_fiscal
   1.2- Agregar el campo id_pais (Tipo de dato: "int") agregar despues de razon social
   1.3- Agregar el campo direccion (Tipo de dato: "text") agregar despues de pais
2- Realizar las siguentes sentencias en orden.
    UPDATE tbl_cliente SET telefono_fiscal = REPLACE(telefono_fiscal,'(','');
    UPDATE tbl_cliente SET telefono_fiscal = REPLACE(telefono_fiscal,')','');
    UPDATE tbl_cliente SET telefono_fiscal = REPLACE(telefono_fiscal,'-','');
    UPDATE tbl_cliente SET telefono_fiscal = REPLACE(telefono_fiscal,' ','');
    UPDATE tbl_cliente SET telefono_fiscal = SUBSTRING(telefono_fiscal,2);
    UPDATE tbl_cliente SET telefono_fiscal = CONCAT('+',' ','58',telefono_fiscal);
    UPDATE tbl_cliente SET id_pais = 240;
3- Agregar nueva tabla a la base de datos. Enviada al correo
4- Actualizar la bd logs. Enviada al correo
5- Los trigger de la tabla cliente cambiaron, asi que hay que modificarlos un poco, y agregar pais y direccion y eliminando id_parroquia, ciudad_fiscal, avenida_calle_fiscal, edificio_quinta_fiscal, piso_fiscal,numero_fiscal. Enviare esa tabla cliente modificada al correo

Que probar?

1- Comprobar el select de paises y el text de direccion el cual no permite guardar hasta que tenga mas de 10 caracteres y se debe ver asi.

![image](https://user-images.githubusercontent.com/59027265/95690250-44d21600-0be4-11eb-8828-645c2f041527.png)

2- verificar que en la consulta aparezca asi

![image](https://user-images.githubusercontent.com/59027265/95690318-d3469780-0be4-11eb-8707-7067c274c027.png)

3- Comprobar el modificar clientes

**Comment by serodriz** [comment]
entrar en los disparadores de clientes y:

1- tbl_cliente_AI  y colocarlo siguiente en definicion

INSERT INTO logs.tbl_cliente(codigo, id_usuario_socio_nuevo, rif_nuevo, nit_nuevo, razon_social_nuevo, id_pais_nuevo, direccion_nuevo, telefono_fiscal_nuevo, pagina_web_nuevo, email_fiscal_nuevo, id_estatus_nuevo) VALUES (NEW.codigo, NEW.id_usuario_socio,  NEW.rif, NEW.nit, NEW.razon_social, NEW.id_pais, NEW.direccion, NEW.telefono_fiscal, NEW.pagina_web, NEW.email_fiscal, NEW.id_estatus)


![image](https://user-images.githubusercontent.com/59027265/95901418-4c6af980-0d61-11eb-8722-2a380f537bdb.png)


2- tbl_cliente_BU  y colocarlo siguiente en definicion


INSERT INTO logs.tbl_cliente(codigo, id_usuario_socio, rif, nit, razon_social, id_pais, direccion, telefono_fiscal, pagina_web, email_fiscal, id_estatus, id_usuario_socio_nuevo, rif_nuevo, nit_nuevo, razon_social_nuevo, id_pais_nuevo, direccion_nuevo, telefono_fiscal_nuevo, pagina_web_nuevo, email_fiscal_nuevo, id_estatus_nuevo) VALUES (NEW.codigo, OLD.id_usuario_socio, OLD.rif, OLD.nit, OLD.razon_social, OLD.id_pais, OLD.direccion, OLD.telefono_fiscal, OLD.pagina_web, OLD.email_fiscal, OLD.id_estatus, NEW.id_usuario_socio, NEW.rif, NEW.nit, NEW.razon_social, NEW.id_pais, NEW.direccion, NEW.telefono_fiscal, NEW.pagina_web, NEW.email_fiscal, NEW.id_estatus)

![image](https://user-images.githubusercontent.com/59027265/95901716-be434300-0d61-11eb-863b-70072a9e2bdc.png)

**Comment by alfiosaglimbeni** [comment]
Referente al cambio que se debe realizar en la BDD fue realizado exitosamente (si bien hubo varios detalles que se tuvieron que ordenar).

con referencia a 
**1- Comprobar el select de paises y el text de direccion el cual no permite guardar hasta que tenga mas de 10 caracteres y se debe ver asi.**
Se realizo una carga de un cliente nuevo y permitió el registro del cliente con una dirección inferior a 10 caracteres, si bien no es vital se debe ajustar el parámetro de validación.
como se muesdtra en esta imagen
![image](https://user-images.githubusercontent.com/22016865/95919744-26068780-0d7c-11eb-9143-52d8c491057d.png)

**Comment by serodriz** [comment]
1- modificar la tabla tbl_cliente
1.1- Eliminar los campos, id_parroquia, ciudad_fiscal, avenida_calle_fiscal, edificio_quinta_fiscal, piso_fiscal,numero_fiscal
1.2- Agregar el campo id_pais (Tipo de dato: "int") agregar despues de razon social
1.3- Agregar el campo direccion (Tipo de dato: "text") agregar despues de pais

2-  modificar la tabla tbl_cliente del logs
2.1- Eliminar los campos, id_parroquia, ciudad_fiscal, avenida_calle_fiscal, edificio_quinta_fiscal, piso_fiscal,numero_fiscal, id_parroquia_nuevo, ciudad_fiscal_nuevo, avenida_calle_fiscal_nuevo, edificio_quinta_fiscal_nuevo, piso_fiscal,numero_fiscal_nuevo
2.2- Agregar el campo id_pais (Tipo de dato: "int" null) agregar despues de razon social
2.3- Agregar el campo direccion (Tipo de dato: "text" null) agregar despues de pais
2.3- Agregar el campo id_pais_nuevo (Tipo de dato: "int" null) agregar despues de razon_social_nuevo
2.5- Agregar el campo direccion_nuevo (Tipo de dato: "text" null) agregar despues de id_pais_nuevo

3- Los trigger de la tabla tbl_cliente de carent cambiaron, asi que hay que modificarlos un poco:
3.1- tbl_cliente_AI y colocar lo siguiente en definicion

INSERT INTO logs.tbl_cliente(codigo, id_usuario_socio_nuevo, rif_nuevo, nit_nuevo, razon_social_nuevo, id_pais_nuevo, direccion_nuevo, telefono_fiscal_nuevo, pagina_web_nuevo, email_fiscal_nuevo, id_estatus_nuevo) VALUES (NEW.codigo, NEW.id_usuario_socio, NEW.rif, NEW.nit, NEW.razon_social, NEW.id_pais, NEW.direccion, NEW.telefono_fiscal, NEW.pagina_web, NEW.email_fiscal, NEW.id_estatus)

3.2-tbl_cliente_BU y colocarlo siguiente en definicion

INSERT INTO logs.tbl_cliente(codigo, id_usuario_socio, rif, nit, razon_social, id_pais, direccion, telefono_fiscal, pagina_web, email_fiscal, id_estatus, id_usuario_socio_nuevo, rif_nuevo, nit_nuevo, razon_social_nuevo, id_pais_nuevo, direccion_nuevo, telefono_fiscal_nuevo, pagina_web_nuevo, email_fiscal_nuevo, id_estatus_nuevo) VALUES (NEW.codigo, OLD.id_usuario_socio, OLD.rif, OLD.nit, OLD.razon_social, OLD.id_pais, OLD.direccion, OLD.telefono_fiscal, OLD.pagina_web, OLD.email_fiscal, OLD.id_estatus, NEW.id_usuario_socio, NEW.rif, NEW.nit, NEW.razon_social, NEW.id_pais, NEW.direccion, NEW.telefono_fiscal, NEW.pagina_web, NEW.email_fiscal, NEW.id_estatus)

4- Agregar nueva tabla tbl_paises a la base de datos. Enviada al correo

5-Realizar las siguentes sentencias en orden en la tabla tbl_cliente
UPDATE tbl_cliente SET telefono_fiscal = REPLACE(telefono_fiscal,'(','');
UPDATE tbl_cliente SET telefono_fiscal = REPLACE(telefono_fiscal,')','');
UPDATE tbl_cliente SET telefono_fiscal = REPLACE(telefono_fiscal,'-','');
UPDATE tbl_cliente SET telefono_fiscal = REPLACE(telefono_fiscal,' ','');
UPDATE tbl_cliente SET telefono_fiscal = SUBSTRING(telefono_fiscal,2);
UPDATE tbl_cliente SET telefono_fiscal = CONCAT('+',' ','58',telefono_fiscal);
UPDATE tbl_cliente SET id_pais = 240;
