### ISSUE TITLE
Actualización en la Base de Datos

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#318]
Se requiere realizar en calidad y en producción después de sus pruebas las siguientes modificaciones en la base de datos:

**1)** En la tabla **logs_auditoria** cambiar el tipo de datos del campo **accion** de **varchar** a **text** debido aque se queda corto en algunas acciones y debemos registrar todo lo que se haga en la base de datos.

**Comment by alfiosaglimbeni** [comment]
Este cambio lo realice el dia de hoy 03/10/2020 a las 1605 en el ambiente de calidad exclusivamente. Quedando pendiente este control de cambio para PRODUCCION
