### ISSUE TITLE
Actualización en la Base de Datos

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#321]
Se requiere cambiar el tipo de datos del campo **horas_trabajadas** de la tabla **tbl_horas_cargables**, el tipo de datos actual es **VARCHAR** de 5 y debe de quedar a tipo **TIME** sin longitud de datos u formato. El cambio se debe realizar tanto en el ambiente de CALIDAD como en PRODUCCIÓN, este último cuando los cambios del issues #315 este en dicha rama.

**Comment by alfiosaglimbeni** [comment]
**En el ambiente de calidad ya se realizó el cambio del tipo de datos
Queda realizarlo en el ambiente de producción**





![cambiodedatocalidad](https://user-images.githubusercontent.com/22016865/95664275-1d137d00-0b14-11eb-9c45-6f7991ef2843.png)
