### ISSUE TITLE
Reporte Horas Cargables

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#322]
Se requiere realizar un reporte que indique la cantidad total de horas cargadas a proyectos de un empleado, gerentes, supervisor, socio etc, y que muestre el nombre del proyecto, cliente, empleado, división.

**Comment by sofguar** [comment]
El día de hoy se modificó la tabla **tbl_menu** y se le agregó un campo llamado **visible** de tipo **booleano** para indicar al sistema que aunque el usuario pueda tener ese menú asociado no se muestre en la barra superior del menú principal. ¿Cuál es el motivo? supongamos que tenemos un menú llamado **Reportes** y que el sistema puede tener **N** reportes, gráficamente es imposible colocar dentro del menú y que se vea bien 100 menús donde cada uno es un reporte, para ellos se creo esa filosofía para poder agregar a cualquier usuario N reportes y que solo al darle click a un menú que los englobe a todos los reportes solo le muestre los reportes que tenga asociado ese usuario. Es decir solo aparecerá un menú llamado Reportes y cuando le de click solo le mostrará los reportes asociados a su usuario, esto puede servir a cualquier otro tipo de circunstancias que amerite asociar un menú pero que no sea necesario mostrarlo en la barra superior del menú principal.

@alfiosaglimbeni para que lo tengas en cuenta.

**Comment by sofguar** [comment]
Para crear el nuevo menú y asociarlo a los usuarios en este caso el 0001 debes de ejecutar los siguientes SQL en el phpmyadmin:

```
INSERT INTO `tbl_menu` (`id`, `id_menu_padre`, `descripcion`, `url`, `orden`, `visible`,  `C`,  `R`, `U`, `D`, `id_estatus`) VALUES (17, 0, 'Reporte ', '/formReportes', 1, 1, 0, 0, 0, 0, 1), (18, 17, 'Reporte de las Horas Cargables', '', 1, 0, 0, 1, 0, 0, 1);
```
y luego

`INSERT INTO `tbl_menu_usuario` (`id`, `id_usuario`, `id_menu`, `C`, `R`, `U`, `D`) VALUES (385, 1, 18, 0, 1, 0, 0);`

**Comment by sofguar** [comment]
@alfiosaglimbeni  así deberia de quedar la tabla con los cambios del #311 y este issues #322
![imagen](https://user-images.githubusercontent.com/55295214/97125005-b9d73c80-1708-11eb-9bf6-717701d0bccd.png)

**Comment by alfiosaglimbeni** [comment]
### este paso ### 
INSERT INTO `tbl_menu` (`id`, `id_menu_padre`, `descripcion`, `url`, `orden`, `visible`,  `C`,  `R`, `U`, `D`, `id_estatus`) VALUES (17, 0, 'Reporte ', '/formReportes', 1, 1, 0, 0, 0, 0, 1), (18, 17, 'Reporte de las Horas Cargables', '', 1, 0, 0, 1, 0, 0, 1);
**listo**

### Y este otro  paso ### 
INSERT INTO tbl_menu_usuario (id_usuario, id_menu, C, R, U, D) VALUES (1, 18, 0, 1, 0, 0);
**listo**

**Comment by sofguar** [comment]
> 
> 
> El día de hoy se modificó la tabla **tbl_menu** y se le agregó un campo llamado **visible** de tipo **booleano** para indicar al sistema que aunque el usuario pueda tener ese menú asociado no se muestre en la barra superior del menú principal. ¿Cuál es el motivo? supongamos que tenemos un menú llamado **Reportes** y que el sistema puede tener **N** reportes, gráficamente es imposible colocar dentro del menú y que se vea bien 100 menús donde cada uno es un reporte, para ellos se creo esa filosofía para poder agregar a cualquier usuario N reportes y que solo al darle click a un menú que los englobe a todos los reportes solo le muestre los reportes que tenga asociado ese usuario. Es decir solo aparecerá un menú llamado Reportes y cuando le de click solo le mostrará los reportes asociados a su usuario, esto puede servir a cualquier otro tipo de circunstancias que amerite asociar un menú pero que no sea necesario mostrarlo en la barra superior del menú principal.
> 
> @alfiosaglimbeni para que lo tengas en cuenta.

El valor del campo **visible** al inicio debe de ser **1** para todos excepto para el menú con le id **18**

**Comment by sofguar** [comment]
@alfiosaglimbeni  ya esta listo este requerimiento, que se debe de probar?

1) Que los filtros en condición de analista, supervisor, gerente, socio, etc funcione y muestre lo que debe de mostrar, ejemplo, si es un socio debería de mostrar todo y si es un gerente debería de mostrar todas las horas de su división y de los cargos que este por debajo de el.

2) Exportar los resultados a excel

3) Que muestre las horas que deberían ser

4) Que este totalizando como Dios manda

**Comment by sofguar** [comment]
Ya se arreglo el problema de los filtros, está listo para pasar a producción

**Comment by sofguar** [comment]
Ya este requerimiento se culminó y esta en rama de producción
