### ISSUE TITLE
Eliminación de clientes duplicados 

### ISSUE THREAD

**Issue by serodriz** [sofguar/carent#344]
Se requiere que se elimine los clientes duplicados

**Comment by serodriz** [comment]
Listo el problema de los clientes duplicados, los cuales no tenían código de cliente, corrección del formulario modificar clientes

Realizar las siguientes sentencias en la tabla tbl_clientes:

1-              DELETE FROM tbl_cliente WHERE codigo IS null;

2-              DELETE FROM tbl_cliente WHERE codigo = 1729;

3-              DELETE FROM tbl_cliente WHERE codigo = 2165;

**Comment by alfiosaglimbeni** [comment]
Actividad realizada satisfactoriamente 03/11/2020 11:49 am

**Comment by sofguar** [comment]
Ya este requerimiento esta en ambiente de producción
