### ISSUE TITLE
Reporte Cantidad de clientes activos/inactivos por divisiones con códigos

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#349]
Se requiere realizar un reporte el cual muestre la cantidad de clientes filtrados por estatus, empresa (Crowe o mpf) y divisiones. Para sacar la empresa se debe cruzar la tabla tbl_proyecto, tbl_empresa y tbl_cliente, ya que el cliente esta asociado al proyetco y al proyecto se le indica la empresa quien lo ejecuta, tambien puedes obtener de alli las divisiones que estan involucradas; con respecto a el estatus es si esta activo o inactivo.

Para referencia de como registrar el menu del reporte en la Base de Datos puede guiarte por el reporte de Horas Cargables que ya esta registrado en la tabla tbl_menu.

Para referencia de como mostrarlo te puede guiar del código que s eimplemento en el reporte Horas Cargables; es imperativo que sigas la filosofia de componentes que se implemento en el reporte de Horas Cargables, es decir guiate como esta arquitectado el codigo de dicho reporte, cualquier cosa me avisas.

**Comment by sofguar** [comment]
@serodriz por favor me pasas el query de inserción del nuevo menú

**Comment by serodriz** [comment]
@dmolina101  ID= 19
INSERT INTO `tbl_menu` (`id`, `id_menu_padre`, `descripcion`, `url`, `orden`, `visible`, `C`, `R`, `U`, `D`, `id_estatus`) VALUES ('19', '17', 'Reporte de Clientes con Proyectos', '', '1', '0', '0', '1', '0', '0', '1');

**Comment by serodriz** [comment]
Reporte de clientes con proyectos finalizado, Probar los filtros de búsqueda de clientes, y realizar la siguiente sentencia en la base de datos:
INSERT INTO tbl_menu (id, id_menu_padre, descripcion, url, orden, visible, C, R, U, D, id_estatus) VALUES ('19', '17', 'Reporte de Clientes con Proyectos', '', '1', '0', '0', '1', '0', '0', '1');

**Comment by alfiosaglimbeni** [comment]
sentencia ejecutada; la misma fué modificada quitandole el id 19 ya que el mismo se encuentra duplicado

**Comment by sofguar** [comment]
Issues ya esta en rama de producción
