### ISSUE TITLE
Reporte cantidad de horas invertidas en un proyecto totales y por gerentes socios y directores

### ISSUE THREAD

**Issue by sofguar** [sofguar/carent#357]
Se requiere diseñar un reporte donde se muestren el total de horas invertidas en un proyecto por usuario; se debe poder filtrar por empleado, código empleado, proyecto, división y cargo

**Comment by serodriz** [comment]
@dmolina101  ID= 22
INSERT INTO tbl_menu (id, id_menu_padre, descripcion, url, orden, visible, C, R, U, D, id_estatus) VALUES ('22', '17', 'Reporte de Horas Invertidas en Proyectos', '', '1', '0', '0', '1', '0', '0', '1');

**Comment by serodriz** [comment]
probar

1.  Agregar horas adicionales a un proyecto y verificar que en el menu: Asi.Personal/Horas Cargables 

> - Ver empleaddos hay un aumento de Horas Contratadas se encuentran las horas previamente asignadas mas las horas adicionales

![image](https://user-images.githubusercontent.com/59027265/101281182-1caa0200-37a4-11eb-9cc9-c38ab9381ee9.png)

> - Asignar ver el si hay un aumento de Horas Asigandas a la división el aumento de las horas adicionales

![image](https://user-images.githubusercontent.com/59027265/101287138-c4cfc300-37c4-11eb-9cef-909ba9b76c85.png)

2. Revisar el reporte de **horas invertidas a proyectos** refleje el monto que tiene el proyecto

**Comment by sofguar** [comment]
Cambio probado y en rama de producción
