### ISSUE TITLE
Notificaciones por correo de las Horas Cargables

### ISSUE THREAD

**Issue by dmolina101** [sofguar/carent#378]
Se requiere implementar como en las **Horas No Cargables** las siguientes notificaciones por correo:

**1)** Cuando un usuario cargue horas cargables notificar a sus superiores excepto a los socios.
**2)** Cuando las horas cargables sean aprobadas por su superior indicarle por correo al analista que las emitió en primer lugar.

Te puedes guiar de como se realizó en las **Horas No Cargables** en los métodos cuando se agrega una nueva hora **no cargable** y cuando se cambia de estatus por un superior por su aprobación.

Debes modificar los parámetros del archivo **.env** donde especificas los parámetros del correo por un tuyo para que veas y pruebes como deben de llegar los correos, yo coloque una cuenta de mailtrap, puedes usar la tuya o usas los parametros de gmail.

**Comment by serodriz** [comment]
Que probar?

1) Cuando un empleado registre las horas cargables llegue un correo de notificación a sus supervisores vía correo.
2) Cuando un supervisor elimina una hora cargable de un empleado, el sistema debe notificarle al empleado vía correo dicha eliminación

**Comment by sofguar** [comment]
Cambio probado y en rama de producción
