### ISSUE TITLE
Reporte total horas cargables y no cargables por empleado

### ISSUE THREAD

**Issue by dmolina101** [sofguar/carent#389]
@serodriz se requiere realizar un reporte que permita generar un listado de profesionales de la firma, y que de forma general, indique la cantidad total de horas cargables, la cantidad total de horas no cargables y la totalización de esas horas, sin la necesidad de detalles como lo son  los clientes, proyectos y conceptos de horas no cargables. Pudiendo aplicar los filtros que consideres necesarios. Este reporte deberá generar un listado completo de todos los profesionales que hayan cargado o no horas en el CARENT.

**Comment by serodriz** [comment]
Agregar el menu con la siguiente consulta:

**INSERT INTO tbl_menu (id, id_menu_padre, descripcion, url, orden, visible, C, R, U, D, id_estatus) VALUES (NULL, '17', 'Reporte total horas cargables y no cargables', '', '1', '0', '0', '1', '0', '0', '1');**

Luego asignar el menú al usuario administrador con la siguiente consulta o desde el mismo sistema

**INSERT INTO tbl_menu_usuario (id, id_usuario, id_menu, C, R, U, D) VALUES (NULL, '1', '25', '0', '1', '0', '0')**

**Comment by serodriz** [comment]
Cosas a tener en cuenta del reporte:
Horas no cargables:

- Al momento de cargar horas no cargables lo haces de la siguiente manera Desde: 01-01-2021 hasta 23-02-2021 El tomara la hora del desde y contara la cantidad de horas que falten para que sean las 17:00 el resto de los días restante los ira tomando como 8 horas, sin contar los días sábado ni el domingo seguirá hasta llegar a la fecha y hora hasta que se cargo.
