### ISSUE TITLE
Agregar información al Reporte de Horas Invertidas en Proyectos

### ISSUE THREAD

**Issue by dmolina101** [sofguar/carent#411]
@serodriz se requiere crear un reporte parecido al de  **Reporte de Horas Invertidas en Proyectos** quitandole las siguientes columnas:

**1)** Empleados
**2)** Montos

y Agregándole las columnas:

**1)** Total horas cargadas por todos los empleados por proyecto
**2)** Total Horas presupuestadas
**3)** Porcentaje entre las horas cargada y las horas presupuestadas, es decir de las horas cargadas cuanto representa frente al total presupuestado
**4)** Horas totales sin horas adicionales
**5)** Horas totales adicionales

Filtros del reporte solo sería Socio del proyecto no el socio de calidad

**Comment by serodriz** [comment]
Agregar el menu con la siguiente consulta:

**INSERT INTO tbl_menu (id, id_menu_padre, descripcion, url, orden, visible, C, R, U, D, id_estatus) VALUES ('26', '17', 'Reporte Total Horas Proyectos', '', '1', '0', '0', '1', '0', '0', '1');**

**Comment by dmolina101** [comment]
Ya estos cambios están en rama de producción
