### ISSUE TITLE
Reporte total horas asignadas por empleado en un rango de fecha indicado

### ISSUE THREAD

**Issue by dmolina101** [sofguar/carent#428]
Se requiere crea un reporte donde: 

1) Se muestre el nombre del empleado
2) Se muestre la división asociada al empleado
3) Cuantas horas ha cargado según el filtro de rango de fechas indicado por el usuario que esta consultando
4) Cual es el porcentaje de carga, es decir el total de horas asignadas entre las horas que ha cargado (Horas Cargables)

El reporte debe ser filtrado por, división, nombre del empleado, rango de fecha (Desde, Hasta)

**Comment by serodriz** [comment]
Agregar el menu con la siguiente consulta:

INSERT INTO tbl_menu (id, id_menu_padre, descripcion, url, orden, visible, C, R, U, D, id_estatus) VALUES (NULL, '17', 'Reporte total horas asignadas por empleado', '', '1', '0', '0', '1', '0', '0', '1');

Comprobar que el id sea el 27

**Comment by serodriz** [comment]
ALTER TABLE `tbl_menu` CHANGE `descripcion` `descripcion` VARCHAR(70) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

UPDATE `tbl_menu` SET `descripcion` = 'Reporte total horas asignadas Vs cargadas por empleado a proyectos' WHERE `tbl_menu`.`id` = 27;

**Comment by serodriz** [comment]
ALTER TABLE tbl_menu CHANGE descripcion descripcion VARCHAR(70) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
INSERT INTO tbl_menu (id, id_menu_padre, descripcion, url, orden, visible, C, R, U, D, id_estatus) VALUES (NULL, '17', 'Reporte total horas asignadas Vs cargadas por empleado a proyectos', '', '1', '0', '0', '1', '0', '0', '1');

**Comment by dmolina101** [comment]
Ye esta en ambiente productivo
