### ISSUE TITLE
Crear un reporte que indique por empleado que fué lo último que cargo en el sistema

### ISSUE THREAD

**Issue by dmolina101** [sofguar/carent#431]
Se requiere crear un reporte que indique por empleado que fue lo último que cargo en el sistema ya sea una hora cargable o no cargable, es decir si lo ultimo que cargo Alfio fue una hora no cargable 2 semanas atrás eso es lo que mostrará el reporte en su fila como empleado. El reporte debe mostrar todos los empleados con sus divisiones, concepto de carga (Proyecto o concepto de hora no cargable), la fecha en que la cargo y si no ha cargado nunca que salga **"No ha cargado nada hasta la fecha"** o algo por el estilo.

Este reporte tiene que tener la opción de exportarlo a excel.

El reporte solo se aplica a los empleados activos.

**Comment by serodriz** [comment]
Agregar el menu con la siguiente consulta:

INSERT INTO tbl_menu (id, id_menu_padre, descripcion, url, orden, visible, C, R, U, D, id_estatus) VALUES (NULL, '17', 'Reporte ultima carga del empleado', '', '1', '0', '0', '1', '0', '0', '1');

Comprobar que el id sea el 28

**Comment by serodriz** [comment]
UPDATE `tbl_menu` SET `descripcion` = 'Reporte última carga a proyectos del empleado' WHERE `tbl_menu`.`id` = 28;

**Comment by serodriz** [comment]
INSERT INTO tbl_menu (id, id_menu_padre, descripcion, url, orden, visible, C, R, U, D, id_estatus) VALUES (NULL, '17', 'Reporte última carga a proyectos del empleado', '', '1', '0', '0', '1', '0', '0', '1');

**Comment by dmolina101** [comment]
Ye esta en ambiente productivo
