### ISSUE TITLE
Actualización de asignación de personal

### ISSUE THREAD

**Issue by dmolina101** [sofguar/carent#432]
Se requiere modificar la asignación del personal y de las horas. Ahorita eso está automático así la asignación al instante pero a veces generaba duplicados, así que se debe crear un botón para asignar hora y personal.

**Comment by serodriz** [comment]
Que probar:

![1](https://user-images.githubusercontent.com/59027265/113032847-555c5580-915e-11eb-8e9e-a85ae669882a.png)

![2](https://user-images.githubusercontent.com/59027265/113032862-5b523680-915e-11eb-8e44-3777716aef95.png)

![4](https://user-images.githubusercontent.com/59027265/113033026-8a68a800-915e-11eb-9a0a-fa59c87dec1a.png)

![5](https://user-images.githubusercontent.com/59027265/113033037-8dfc2f00-915e-11eb-9d00-b1608f28e524.png)

**Comment by dmolina101** [comment]
Ye esta en ambiente productivo
