### ISSUE TITLE
Corrección del módulo de horas cargables

### ISSUE THREAD

**Issue by dmolina101** [sofguar/carent#471]
Actualmente existe un hueco en el sistema el cual contempla que cuando un empleado renuncia las horas cargables previamente cargadas desaparecen del registro de dichas hora y se pueden volver a cargar o asignar a otro empleado y no deberia de ser así; las horas cargadas deben de verse reflejadas aunque el empleado cambie de estatus

**Comment by serodriz** [comment]
cosas para revisar:

Entrar en la asignación de empleados a proyectos. Y verificar lo siguiente:

1. Si un empleado ya ha cargado horas no pueda ser eliminado
2. Si un empleado ya ha cargado horas y se le reducen las horas asignadas estas no pueden ser menor a la horas ya cargadas previamente.
3. Si un empleado se encuentra inactivo no aparezca en la lista de empleados ha asignar
   3.1.  Si el empleado ya antes de estar inactivo fue asignado al proyecto y luego eliminado si se visualizara en la lista (Esto ocurrirá motivo del punto 2)
