### ISSUE TITLE
Actualización del formulario crear cliente

### ISSUE THREAD

**Issue by dmolina101** [sofguar/carent#475]
Se requiere actualizar el formulario de crear un nuevo cliente con respecto a:

**1)** Migrar el codigo html a como lo plantea usando el componente bootstrap-vue; puedes guiarte del formulario que esta en la ruta `resources\views\facturacion\agregarIngresosGastos.blade.php`

**2)** Una vez te fijes en el código fuente de dicho formulario veras que hay complementos como el **login**, **alert** y **confirm** que se emplean, tambien debes de integrarlo en esta actualización, por ejemplo: cuando se vaya a crear un cliente deberia de salir una confirmación preguntando si en verdad esta seguro de crear dicho cliente.

**3)** Usar como validador del formulario **Vuelidate**

**4)** Actualmente el formulario posee ayudas con asteriscos en rojo para indicar si los campos son obligatorios, ya eso no hace falta, puedes eliminarlo.

![Sin título1](https://user-images.githubusercontent.com/24720946/122287168-a870b980-cebe-11eb-960a-53433c5261ec.jpg)

**5)** El css de los botones y del formulario trata de que sea igual al del login

**6)** Implementar un procedimiento almacenado en el modelo que haga la función o la tarea de crear un nuevo cliente y este a su vez registre por bitacora, puedes guiarte del procedimiento almacenado **sp_usuario_cambia_su_clave**. La sugerencia para llamar al procedimiento seria **sp_nuevo_cliente**, ya seria cuestión tuya como lo quieras llamar

**7)** Se que a veces no es facil tratar de darle un sentido a los formularios pero trata de que los campos en **Dirección Fiscal** queden parejos es decir por ejemplo colocar dirección arriba, luego pais y al lado de pais numero de telefono luego en la fila de abajo **Correo** y **Pagina Web**

Cualquier duda o prgeunta hazmela saber

**Comment by serodriz** [comment]
Código fue migrado al ultimo estándar de bootstrap-vue.

y ejecutar el siguiente sql que contiene el procedimiento: sp_nuevo_cliente

DELIMITER $$
CREATE DEFINER=`root`@`127.0.0.1` PROCEDURE `sp_nuevo_cliente`(IN `p_id_usuario` INT, IN `p_id_usuario_socio` INT, IN `p_codigo_cliente` INT, IN `p_rif` VARCHAR(30), IN `p_razon_social` VARCHAR(60), IN `p_id_pais` INT, IN `p_direccion` TEXT, IN `p_telefono_fiscal` VARCHAR(30), IN `p_pagina_web` VARCHAR(150), IN `p_email_fiscal` VARCHAR(100), IN `p_ip_accion` VARCHAR(40), OUT `p_respuesta` TEXT)
BEGIN
  DECLARE v_fecha_creacion_cliente DATE;
  DECLARE v_sql_bitacora TEXT;
    
  DECLARE v_custom_msg_error TEXT DEFAULT NULL;
  DECLARE v_sql_string TEXT DEFAULT NULL;
  DECLARE custom_error CONDITION FOR SQLSTATE '45000';
    
  DECLARE EXIT HANDLER FOR SQLEXCEPTION, SQLWARNING
    BEGIN 
      ROLLBACK;
        GET DIAGNOSTICS CONDITION 1 @code = RETURNED_SQLSTATE, @error_string = MESSAGE_TEXT;
        SELECT CONCAT('Error con el código ',@code,': ',@error_string) INTO v_custom_msg_error;  
        CALL sp_mensaje_bd(1,1,"sp_nuevo_cliente",v_custom_msg_error,NULL,1,@response);
        SET p_respuesta = '{ 
          "message":"Ocurrió un error a la hora de crear el cliente!",
      	  "response": false
    	}';
      COMMIT;  
  END;
  DECLARE EXIT HANDLER FOR custom_error 
    BEGIN
      ROLLBACK;
        IF v_custom_msg_error IS NOT NULL THEN
          CALL sp_mensaje_bd(1,1,"sp_nuevo_cliente",v_custom_msg_error,v_sql_string,1,@response);
        END IF;
        IF p_respuesta = "" OR p_respuesta IS NULL THEN
          SET p_respuesta = '{
            "message": "Ocurrió un error a la hora tratar de actualizar su contraseña!",
            "response": false
      }';
        END IF;
      COMMIT;
  END;
  START TRANSACTION;
    SELECT DATE_ADD(CURDATE(), INTERVAL 60 DAY) INTO v_fecha_creacion_cliente;
    INSERT INTO `tbl_cliente`(`id`, `id_usuario_socio`, `codigo`, `rif`, `nit`, `razon_social`, `id_pais`, `direccion`, `telefono_fiscal`, `pagina_web`, `email_fiscal`, `id_estatus`) VALUES (null, p_id_usuario_socio, p_codigo_cliente, p_rif, null, p_razon_social, p_id_pais, p_direccion, p_telefono_fiscal, p_pagina_web, p_email_fiscal, 1);
    SET v_sql_bitacora = CONCAT('INSERT INTO tbl_cliente (id, id_usuario_socio, codigo, rif, nit, razon_social, id_pais, direccion, telefono_fiscal, pagina_web, email_fiscal, id_estatus) VALUES (null, "',p_id_usuario_socio,'", "',p_codigo_cliente,'", "',p_rif,'", null, "',p_razon_social,'", "',p_id_pais,'", "',p_direccion,'", "',p_telefono_fiscal,'", "',p_pagina_web,'", "',p_email_fiscal,'", 1)');
    SET @nuevo_valor = CONCAT('{"id_usuario_socio": "',p_id_usuario_socio,'", "codigo": "',p_codigo_cliente,'", "rif": "',p_rif,'", "razon_social": "',p_razon_social,'", "id_pais": "',p_id_pais,'", "direccion": "',p_direccion,'", "telefono_fiscal": "',p_telefono_fiscal,'", "pagina_web": "',p_pagina_web,'", "email_fiscal": "',p_email_fiscal,'", "id_estatus": ",1,"}');
    CALL sp_bitacora(1,"crear_cliente",p_id_usuario,p_id_usuario,"tbl_cliente",v_sql_bitacora,@valor_anterior,@nuevo_valor,p_ip_accion,@response);   
    SET @v_respuesta_otro_sp = JSON_UNQUOTE(JSON_EXTRACT(@response,'$.response'));
    IF @v_respuesta_otro_sp = "true" THEN
      SET p_respuesta = CONCAT('{
        "message": "Cliente Creado con Éxito.",
        "response":true
      }');
      COMMIT;
    ELSE
      SET p_respuesta = '{
        "message":"Ocurrió un error a la hora de crear el cliente, no se pudo registrar en Bitácora!",
        "response":false
      }';
      ROLLBACK;
    END IF;
END$$
DELIMITER ;

**Comment by alfiosaglimbeni** [comment]
Este SP se realizo en otro ISSUE
