### ISSUE TITLE
Actualización de Objetos en la Base de Datos

### ISSUE THREAD

**Issue by dmolina101** [sofguar/carent#479]
Muy buenos días @alfiosaglimbeni, hay que hacer unos cambios en la base de Datos para que funcione bien el registro de los mensajes a nivel de base de datos, es decir, si ocurre un error se registre como deben de ser:

**1)** Verificar si existe el estatus "**tbl_mensaje_bd**" esta en la tabla **tbl_estatus**; como verificas? bueno entras en la tabla **tbl_estatus** y  buscas por el campo **tabla** el que tenga como valor **tbl_mensaje_bd**, si **NO** lo tienes registrado en esa tabla por favor crearlo con los siguientes valores: en el campo **tabla** colocas **tbl_mensaje_bd**, en el campo **valor** colocas **1** y en el campo descripción colocas **"sin leer"**, el **id** de dicha tabla se genera automatico por lo que puedes dejarlo vacio para que se autocomplente en el momento de que se ejecute el **INSERT**

**2)** Debemos cambiar algunos procedimientos almacenados, para ello debes eliminarlos y volverlos a crear con los scripts que se te adjuntare a continuación:

2.1) sp_login
[sp_login.txt](https://github.com/sofguar/carent/files/7034586/sp_login.txt)

2.2) sp_resetar_claves_usuarios
[sp_resetar_claves_usuarios.txt](https://github.com/sofguar/carent/files/7034587/sp_resetar_claves_usuarios.txt)

2.3) sp_recuperar_login
[sp_recuperar_login.txt](https://github.com/sofguar/carent/files/7034589/sp_recuperar_login.txt)

2.4) sp_nuevo_cliente
[sp_nuevo_cliente.txt](https://github.com/sofguar/carent/files/7034616/sp_nuevo_cliente.txt)

2.5) sp_usuario_cambia_su_clave
[sp_usuario_cambia_su_clave.txt](https://github.com/sofguar/carent/files/7034595/sp_usuario_cambia_su_clave.txt)

**Comment by alfiosaglimbeni** [comment]
Se ejecutaron los pasos 1 y los 2 de este issue
