### ISSUE TITLE
Agregar IVA y ISRL al módulo de facturación

### ISSUE THREAD

**Issue by dmolina101** [sofguar/carent#518]
La modificación planteada por el equipo del Señor José  Machado es la siguiente, se requiere agregar al modulo actual, la capacidad de registrar las retenciones de los impuestos que realicen los clientes de la Firma.

Las retenciones que se deben registrar son DOS (02) impuestos a mencionar Impuesto al Valor Agregado (IVA) y las del Impuesto Sobre la Renta (ISLR)

Para el caso del IVA se deben tomar en cuenta las siguientes consideraciones:

- El cliente puede retener el 75% del monto del IVA o
- El cliente puede retener el 100% del monto del IVA

EJEMPLO:

SubTotal: 1.000,00
IVA (16%): 160,00
Total: 1.160,00

- Si el cliente realiza una retención del 75% del IVA el monto retenido por el mismo es de 120,00 entregando un pago total de 1.040,00 (1.000,00 + 40,00).
- Si el cliente realiza una retención del 100% del IVA el monto retenido por el mismo es de 160,00 entregando un pago total de 1.000,00 (1.000,00 + 0,00).

El sistema debe tener la capacidad de registrar UNA de las DOS opciones, esta seleccion pudiera ser usando un "ComboBox" o un "RadioButton" a conveniencia del desarrollador.

Para el caso del ISLR se deben tomar en cuenta las siguientes consideraciones:

- El cliente puede retener el 2% del monto de SubTotal de la Factura,
- El cliente puede retener el 3% del monto de SubTotal de la Factura,
- El cliente puede retener el 5% del monto de SubTotal de la Factura

EJEMPLO:

- Si el cliente realiza una retención del 2% del monto SubTotal (1.000,00 x 2% = 20,00) entregaría a la Firma 980,00 (1.000,00 - 20,00).
- Si el cliente realiza una retención del 3% del monto SubTotal (1.000,00 x 3% = 30,00) entregaría a la Firma 970,00 (1.000,00 - 30,00).
- Si el cliente realiza una retención del 5% del monto SubTotal (1.000,00 x 5% = 50,00) entregaría a la Firma 950,00 (1.000,00 - 50,00).

El cliente retiene el 75% del IVA y el 3% del ISLR, se debería registrar en el modulo de facturación del CARENT la siguiente información:

<html>
<body>

Retención IVA | Porcentaje |   | Monto retenido
-- | -- | -- | --
  | 75,00 % | X | 10.215,09
  | 100,00% (  ) |   |  
  | IVA Cancelado |   | 3.405,03
  |   |   |  
Retención ISLR | Porcentaje |   | Monto retenido
  | 2,00 % |   |  
  | 3,00 % | X | 2.553,77
  | 5,00 % |   |  
  | Monto Cancelado |   | 82.57

</body>
</html>

Debemos recordar que el cliente puede cancelar el monto total de la factura en 1, 2, 3 o 4 partes y se debe registrar las retenciones en cada uno de los pagos parciales.

**Comment by dmolina101** [comment]
Hay que hacer un cambio en el archivo **config\database.php** en la linea 59 que dice:

`'strict' => true,`

Ahora pasa a 

`'strict' => false,`

**Comment by dmolina101** [comment]
Se debe de agregar los campos en la **tabla tbl_factura_proyecto** los campos **id_iva**, **id_porcentaje_retencion_iva** y **id_deduccion_islr** y van despues del campo **monto_factura**. El tipo de datos de ambos campos es **INT** y pueden ser **NULL**

**Comment by dmolina101** [comment]
Creamos la tabla **tbl_iva**:

```
CREATE TABLE tbl_iva (
  id int(11) NOT NULL,
  descripcion varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL,
  valor decimal(5,2) NOT NULL,
  id_estatus int(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


ALTER TABLE tbl_iva
  ADD PRIMARY KEY (`id`);

INSERT INTO tbl_iva (id, descripcion, valor, id_estatus) VALUES
(0, 'No definido', '0', 2),
(1, '16%', '16.00', 1),
(2, '8%', '8.00', 1);

ALTER TABLE tbl_iva
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;

```

Creamos la tabla **tbl_porcentaje_retencion_iva** con el siguiente sql:

```
CREATE TABLE tbl_porcentaje_retencion_iva (
  id int(11) NOT NULL,
  descripcion varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL,
  valor decimal(5,2) NOT NULL,
  id_estatus int(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE tbl_porcentaje_retencion_iva 
  ADD PRIMARY KEY (id);

```

Creamos los registros iniciales

```
INSERT INTO tbl_porcentaje_retencion_iva (id, descripcion, valor, id_estatus) VALUES
(0, 'No definido', '0', 2),
(1, '100%', '100.00', 1),
(2, '75%', '75.00', 1);

ALTER TABLE `tbl_porcentaje_retencion_iva`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;

```

**Comment by dmolina101** [comment]
Debemos tambien crear la siguiente tabla llamada **tbl_deduccion_islr**:

```
CREATE TABLE tbl_deduccion_islr (
  id int(11) NOT NULL,
  descripcion varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL,
  valor decimal(5,2) NOT NULL,
  id_estatus int(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE tbl_deduccion_islr
  ADD PRIMARY KEY (id);
```
Creamos los registros iniciales

```
INSERT INTO tbl_deduccion_islr (id, descripcion, valor, id_estatus) VALUES
(0, 'No definido', '0', 2),
(1, '2%', '2.00', 1),
(2, '3%', '3.00', 1),
(3, '5%', '5.00', 1);

ALTER TABLE tbl_deduccion_islr
  MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
COMMIT;
```

**Comment by dmolina101** [comment]
Agregamos los siguientes estatus:

INSERT INTO tbl_estatus (tabla, valor, descripcion) VALUES ('tbl_porcentaje_retencion_iva', '1', 'activo'), ('tbl_porcentaje_retencion_iva', '2', 'inactivo'), ('tbl_deduccion_islr', '1', 'activo'), ('tbl_deduccion_islr', '2', 'inactivo'),('tbl_iva', '1', 'activo'), ('tbl_iva', '2', 'inactivo');

**Comment by dmolina101** [comment]
Se valido que solo el IVA y el ISLR sea aplicado a los conceptos de factura: Facturación, Gastos No Presupuestados y Otros Gastos en la modal de agregar nueva factura.

**Comment by alfiosaglimbeni** [comment]
OBSERVACIONES:
1) Todos los campos  descripcion definidos como varchar(10) fueron cambiados por varchar(15)
2) En la consulta: "INSERT INTO tbl_porcentaje_retencion_iva (id, descripción, valor, id_estatus) VALUES..." se cambio "descripción" por "descripcion" ya que fue definida de esa forma al crear la tabla.

**Comment by alfiosaglimbeni** [comment]
Hice los cambios de este isssue y al realizar las pruebas funcionales me genraron un error que documento en este archivo anex
[incidencia en calidad.docx](https://github.com/geekstvzla/carent/files/7654235/incidencia.en.calidad.docx)
o

**Comment by alfiosaglimbeni** [comment]
**Se realizo este cambio**

         _'strict' => true,

Ahora pasa a

         'strict' => false,_

**LISTO**

**Comment by alfiosaglimbeni** [comment]
**el siguiente proceso**

_Se debe de agregar los campos en la tabla tbl_factura_proyecto los campos id_iva, id_porcentaje_retencion_iva y id_deducion_islr y van despues del campo monto_factura. El tipo de datos de ambos campos es INT y pueden ser NULL_

**Fue realizado satisfactoriamente**

**Comment by alfiosaglimbeni** [comment]
**Al crear la tabla tbl_iva con la siguiente sentencia:**

_CREATE TABLE tbl_iva ( id int(11) NOT NULL, descripcion varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL, valor decimal(5,2) NOT NULL, id_estatus int(1) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci_

**arrojo la siguiente advertencia:**

 _Warning: #1681 Integer display width is deprecated and will be removed in a future release._

**De igual manera al ejecutar la sentencia:**

_ALTER TABLE tbl_iva MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3_ 

**arrojo la misma advertencia:**

 _Warning: #1681 Integer display width is deprecated and will be removed in a future release._

### ACTIVIDAD LISTA

**Comment by alfiosaglimbeni** [comment]
**Para todos los  "_COMMIT_;" de este ISSUE el MySQL indicaba error, los mismos no fueron incluidos en la ejecuciòn de las mismas.**

**Comment by alfiosaglimbeni** [comment]
**Se ejecuto la setencia**

_INSERT INTO tbl_estatus (tabla, valor, descripcion) VALUES ('tbl_porcentaje_retencion_iva', '1', 'activo'), ('tbl_porcentaje_retencion_iva', '2', 'inactivo'), ('tbl_deduccion_islr', '1', 'activo'), ('tbl_deduccion_islr', '2', 'inactivo'),('tbl_iva', '1', 'activo'), ('tbl_iva', '2', 'inactivo');_

### Y se cargo satisfactoriamente
