### ISSUE TITLE
Crear el procedimiento almacenado para actualizar un cliente

### ISSUE THREAD

**Issue by dmolina101** [sofguar/carent#574]
Se requiere crear el procedimiento almacenado para actualizar un cliente, puede agarrar como ejemplo el procedimiento que crea un nuevo cliente llamado **sp_nuevo_cliente**, el nombre sugerido para el nuevo procedimiento seria **sp_update_client**, se coloca de esta forma porque la idea es ir migrando los objetos de la base de datos a una neva nomenclatura donde indique en este caso la acción UPDATE y la tabla que esta tocando **CLIENTE**, solo que se coloca **client** en ingles para hacerlo mas comercial.

El procedimiento debe ser invocado en el modelo de la aplicación que esta en la siguiente ruta:

app/Models/ClienteModel.php

La función que debe llamar dicho procedimiento es **modificarCliente**

**Nota:** el procedimiento tiene que manejar los errores, cosa que si ocurre debe registrarlo en una tabla, dicho procedimiento se llama **sp_mensaje_bd**, de igual manera en los otros procedimiento te puedes guiar como se utiliza, tambien el procedimento debe registrar en bitacora, el procedimiento para tal acción es **sp_bitacora**

Cualquier duda o pregunta estamos a la orden

**Comment by Eifen** [comment]
[Procedure Update.txt](https://github.com/geekstvzla/carent/files/10817764/Procedure.Update.txt)

**Comment by dmolina101** [comment]
Procedimiento probado en mi local, voy hacer un archivo de migracion el cual tiene la estrutura del objecto cosa que al ejecutar el comando `php artisan migrate` se cree el objeto automáticamente. El directorio donde van los objeto de la base de datos estan en  `database/migrations/`

**Nota:** Cambie el nombre del metodo en el controlador y modelo para actualizar al cliente y lo coloque en ingles para hacerlo más comercial, la idea es ir colocando todo en ingles para ese objetivo

@Eifen

**Comment by dmolina101** [comment]
Se creo el archivo de migracion llamado `client_1_create_sp_update_client_stored_procedure.php` puedes obtener los cambios @Eifen, revisa y me comentas para unirla a calidad

**Comment by Eifen** [comment]
Se ha actualizado el procedure de crear y actualizar cliente
[Procedure create - update client.txt](https://github.com/geekstvzla/carent/files/11498709/Procedure.create.-.update.client.txt)

**Comment by dmolina101** [comment]
Listo, lo actualice los archivos migrate
