### ISSUE TITLE
Agregar nuevos campos para el formulario de crear cliente

### ISSUE THREAD

**Issue by dmolina101** [sofguar/carent#576]
Estan requiriendo almacenar unos datos adicionales para registrar un nuevo cliente, dichos datos son:

**Sector:** privado o público.
**Servicios:**  Financiero, Manufactura, Energético, Salud, Seguros, Agroalimentario, Telecomunicaciones, Fintech, Construcción, Automotriz, Servicios, Agrícola, Distribución, Logística, Almacenaje y ONG/Fundaciones.

Los nuevos campos tienen que ser **select:options** (Lista o combo), para ello deben ser llenados con data proveniente de tablas que contenga dicha información. El nombre sugerido para dichas tablas seria **tbl_sector** y **tbl_servicio**.

Las tablas tienen que tener un ID el cual pueda servir como referencia a la hora de guardar dicho valor en la tabla cliente, es decir en la tabla cliente **tbl_cliente** debe de existir unos campos llamado **id_sector** y **id_servicio** que almacenarian el id seleccionado desde el formuario para el sector y servicio seleccionado.

Hay que validar dichos campos, es decir, que sean obligatorios.

**Comment by Eifen** [comment]
Anexo adjunto del procedure

Datos a tener en cuenta:
[procedure nuevo cliente.txt](https://github.com/geekstvzla/carent/files/10874076/procedure.nuevo.cliente.txt)

- Se soluciono un bug sobre uno de los campos del formulario de crear cliente en el branch #577
