### ISSUE TITLE
Agregar nuevos campos para el formulario de actualizar cliente

### ISSUE THREAD

**Issue by dmolina101** [sofguar/carent#577]
Estan requiriendo almacenar unos datos adicionales para actualizar un cliente, dichos datos son:

**Sector:** privado o público.
**Servicios:** Financiero, Manufactura, Energético, Salud, Seguros, Agroalimentario, Telecomunicaciones, Fintech, Construcción, Automotriz, Servicios, Agrícola, Distribución, Logística, Almacenaje y ONG/Fundaciones.

Los nuevos campos tienen que ser select:options (Lista o combo), para ello deben ser llenados con data proveniente de tablas tbl_sector y tbl_servicio.

Hay que validar dichos campos, es decir, que sean obligatorios, y estos datos deben ser pasado como parametros en el procedimiento de actualización sp_actualizar_cliente

**Comment by Eifen** [comment]
Actividad culminada:

- Se soluciono un problema con uno de los campos del crear cliente en este branch
- Se elimino el clearselection de los v-select de los campos a modificar
- Anexo procedure de actualizar cliente: 
[procedure actualizar cliente.txt](https://github.com/geekstvzla/carent/files/10874088/procedure.actualizar.cliente.txt)

**Comment by Eifen** [comment]
Scripts de las tablas sector y servicio
[tbl_servicio(1).zip](https://github.com/geekstvzla/carent/files/11466709/tbl_servicio.1.zip)
[tbl_sector(1).zip](https://github.com/geekstvzla/carent/files/11466710/tbl_sector.1.zip)
