### ISSUE TITLE
Crear el procedimiento almacenado para crear un nuevo proyecto

### ISSUE THREAD

**Issue by dmolina101** [sofguar/carent#579]
Actualmente para crear un proyecto se inserta directo en el modelo **app/Models/ProyectoModel.php** a través de la función **crearProyecto**; si te fijas podras ver que se inserta en dos tablas tanto en **tbl_proyecto** y **tbl_proyecto_divisiones**, entonces en el procedimiento debes hacer lo mismo que en esa función, insertar en la tabla **tbl_proyecto** luego obtener el id generado del último insert y con ese insertar en **tbl_proyecto_divisiones** para relacionar los registros con el proyecto.

**Comment by Eifen** [comment]
Commit subido #579
[procedure branch 579.txt](https://github.com/geekstvzla/carent/files/10913152/procedure.branch.579.txt)
